
platform :ios, '8.0'

target 'DRSalesforceInterface_Example', :exclusive => true do

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

  use_frameworks!
  pod 'DRSalesforceInterface', :path => '../'
  pod 'SalesforceSDKCore'
  pod 'SalesforceNetwork'
  pod 'SalesforceRestAPI'
  pod 'SmartStore'
  pod 'SmartSync'
  
end
